# Generated by Django 6.0.3 on 2026-04-14 20:04

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_code', models.CharField(max_length=20)),
                ('food_name', models.CharField(max_length=100)),
                ('food_group', models.CharField(max_length=20)),
                ('water', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('energy_kcal', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('starch', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('total_sugars', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('glucose', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('galactose', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('fructose', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('sucrose', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('maltose', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('lactose', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('alcohol', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('nsp', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('aoac_fibre', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('cholesterol', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('potassium', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('magnesium', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('phosphorus', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('iron', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('copper', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('zinc', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('chloride', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('manganese', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('selenium', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('iodine', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('retinol', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('carotene', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('retinol_equivalent', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('vitamin_d', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('vitamin_e', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('vitamin_k1', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('thiamin', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('riboflavin', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('miacin', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('tryptophan', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('niacin_equivalent', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('vitamin_b6', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('vitamin_b12', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('folate', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('pantothenate', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('biotin', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('vitamin_c', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('food_name_lcase', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal_contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=255)),
                ('potassium', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('magnesium', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('energy_kcal', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_code', models.CharField(max_length=20)),
                ('mass', models.IntegerField(null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_adder.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Mealitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.IntegerField(null=True)),
                ('food_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_adder.food_data')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_adder.meal')),
            ],
        ),
    ]
