# Generated by Django 6.0.3 on 2026-03-26 17:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_adder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
